# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='nulo', max_length=100, verbose_name='Tipo')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=25, verbose_name='Numero')),
                ('emissao', models.DateTimeField(auto_now_add=True, verbose_name='Emissao')),
                ('vencimento', models.DateTimeField(auto_now_add=True, verbose_name='Vencimento')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
            ],
            managers=[
                ('documento', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='nulo', max_length=2048, verbose_name='Descricao')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Cep')),
                ('tipo', models.CharField(default='nulo', max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(default='nulo', max_length=2048, verbose_name='Descricao')),
                ('complemento', models.CharField(default='nulo', max_length=2048, verbose_name='Complemento')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Numero')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Finaceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Parcela')),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor')),
                ('desconto', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_pago', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Valor_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(default='nulo', max_length=100, verbose_name='Produto')),
                ('quantidade', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='null.jpg', null=True, upload_to='produto/')),
                ('descricao', models.CharField(default='nulo', max_length=2048, verbose_name='Descricao')),
                ('unidade', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Unidade')),
                ('estoque', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='nulo', max_length=2048, verbose_name='Descricao')),
                ('fator', models.CharField(default='nulo', max_length=2048, verbose_name='Fator')),
            ],
        ),
    ]
