# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.AlterModelManagers(
            name='documento',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Documento'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Email'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Endereco'),
        ),
    ]
