# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0004_auto_20160522_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=100, verbose_name='Nome')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Documento')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Email')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clintes',
            },
        ),
        migrations.RenameModel(
            old_name='Finaceiro',
            new_name='Financeiro',
        ),
        migrations.AddField(
            model_name='venda',
            name='finaceiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Financeiro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='fornecedor/static/imagens/default.jpg', null=True, upload_to='produto/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Unidade'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Cliente'),
            preserve_default=False,
        ),
    ]
