# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0005_auto_20160522_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='finaceiro',
            new_name='financeiro',
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_pago',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor_pago'),
        ),
    ]
