# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0006_auto_20160522_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
