# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0008_auto_20160525_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='fornecedor/static/imagens/default.jpg', null=True, upload_to='produto/'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='foto',
            field=models.ImageField(blank=True, default='fornecedor/static/imagens/default.jpg', null=True, upload_to='produto/'),
        ),
    ]
