# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0009_auto_20160525_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
    ]
