# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0010_auto_20160526_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='foto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='emailcliente',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='emailfornecedor',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
