# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0011_auto_20160526_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='emailcliente',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='emailfornecedor',
        ),
        migrations.AlterField(
            model_name='email',
            name='descricao',
            field=models.EmailField(max_length=254),
        ),
    ]
