# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0012_auto_20160526_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
    ]
