# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0013_remove_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='valorparcela',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ValorParcela'),
        ),
    ]
