# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0015_auto_20160526_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
    ]
