# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0016_remove_produto_fornecedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
